name: Update data.csv

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch data from API and append to data.csv
        run: |
          curl -s https://script.google.com/macros/s/AKfycbzSb9XVwkLzyyJY6ileivj1gThZI9juwonQ50hhGThJ6b5mMY08GL2g_2heLgxzGcY/exec -o latest.json
          if [ ! -f data.csv ]; then
            echo "localTime,temperature,humidity,counts,cps,uSv,timestamp,stationName" > data.csv
          fi
          jq -r '[.localTime, .temperature, .humidity, .counts, .cps, .uSv, .timestamp, .stationName] | @csv' latest.json >> data.csv

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.csv
          git commit -m "Append new data" || echo "No changes to commit"
          git push
